'From Cuis 4.2 of 25 July 2013 [latest update: #1808] on 24 August 2013 at 5:18:46.413534 pm'!
'Description Please enter a description for this package'!
!provides: 'Aida-Installer' 1 0!
!requires: 'Cuis-Network-MIME' 1 0 nil!
!requires: 'Cuis-Network-UUID' 1 0 nil!
!requires: 'Cuis-NetworkTests-UUID' 1 0 nil!
!requires: 'Cuis-Network-RFC822' 1 0 nil!
!requires: 'Cuis-Settings-Network' 1 0 nil!
!requires: 'Cuis-NetworkTests-Protocols' 1 0 nil!
!requires: 'Cuis-NetworkTests-RFC822' 1 0 nil!
!requires: 'Swazoo-Installer' 1 0 nil!
!requires: 'Aida' 1 0 nil!
!classDefinition: #AidaInstaller category: #'Aida-Installer'!
Object variableByteSubclass: #AidaInstaller
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Aida-Installer'!
!classDefinition: 'AidaInstaller class' category: #'Aida-Installer'!
AidaInstaller class
	instanceVariableNames: ''!

